export class EventList {


    static events = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: 'Marston Breezeway',
            name: 'Sponsors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: 'Marston Breezeway',
            name: 'Mentors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547857800000,
            location: 'Marston Breezeway',
            name: 'Hacker Check-In',
            startTime: 1547850600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: 'Marston Breezeway',
            name: 'Bolay Dinner',
            startTime: 1547852400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: 'CSE E222',
            name: 'Team Building Activity',
            startTime: 1547854200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547863200000,
            location: 'Carleton',
            name: 'Opening Ceremony',
            startTime: 1547859600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547866800000,
            location: 'Marston Basement',
            name: 'Sponsor Fair',
            startTime: 1547863200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: null,
            location: '',
            name: 'Hacking Begins!!',
            startTime: 1547866800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: 'Visualization Room',
            name: 'SwampTank Activity',
            startTime: 1547869500000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: 'CSE E222',
            name: 'Intro to Git and Github',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547872500000,
            location: 'CSE E119',
            name: 'Survival Guide w/ JP Morgan',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: 'Marston 2nd Floor',
            name: 'Midnight Snack from KIND',
            startTime: 1547874000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'quarterHalf',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547876700000,
            location: 'CSE E119',
            name: 'Intro to Frontend (HTML/CSS)',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: 'CSE E221',
            name: 'iOS Development in Swift',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547881200000,
            location: 'CSE E119',
            name: 'VR on the Web',
            startTime: 1547877600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547878800000,
            location: 'CSE E220',
            name: 'Extreme Rock Paper Scissors',
            startTime: 1547877600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547911800000,
            location: 'Marston 2nd Floor',
            name: 'Ping Pong Tournament by InfoTech',
            startTime: 1547908200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547884800000,
            location: 'CSE E220',
            name: 'Intro to Reverse Engineering',
            startTime: 1547881200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547902800000,
            location: 'Marston Breezeway',
            name: 'Slime Station by Microsoft',
            startTime: 1547899200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547906400000,
            location: 'Marston Breezeway',
            name: 'Flying Biscuit Breakfast',
            startTime: 1547902800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: 'quarterHalf',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: 'Visualization Room',
            name: 'Citi Workshop - Nontechnical skills that set you apart for internships',
            startTime: 1547946000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: 'CSE E222',
            name: 'Building a Backend with Python and Flask',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547912700000,
            location: 'CSE E220',
            name: 'Microsoft Lightning talk - Getting Started with Artificial Intelligence and Machine Learning',
            startTime: 1547911800000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: 'Marston 2nd Floor',
            name: 'Snack Release by Amex',
            startTime: 1547913000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917200000,
            location: 'Marston Breezeway',
            name: 'Pancake Art',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: 'Marston Breezeway',
            name: 'Musical Chairs by Ultimate Software',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: 'CSE E221',
            name: 'Pitching Your New Business Venture',
            startTime: 1547913600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919000000,
            location: 'CSE E220',
            name: 'Advanced Frontend (Angular/React)',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917500000,
            location: 'CSE E121',
            name: 'InfoTech Workshop',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547920800000,
            location: 'Marston 2nd Floor',
            name: 'POWER HOUR - Citi',
            startTime: 1547917200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919300000,
            location: 'CSE E221',
            name: 'Home Depot Workshop - Intro to Docker',
            startTime: 1547917200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547922600000,
            location: 'Marston Breezeway',
            name: 'Therapy Dogs by Realtruck',
            startTime: 1547919000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: 'Marston Breezeway',
            name: 'Mi Apa Lunch by Citi',
            startTime: 1547920800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: 'Marston Breezeway',
            name: 'Chubby Bunny Game by Amex',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: 'Visualization Room',
            name: 'Jackbox Games by Home Depot',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547927100000,
            location: 'CSE E220',
            name: 'ExxonMobil Lightning Talk - Live demo on full stack web application using React, Express (Node.js) and Mongo',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: 'Marston 2nd Floor',
            name: 'Paper Airplane Comp',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547927100000,
            location: 'CSE E221',
            name: 'Infinite Energy Lightning talk 1 - Intro to Docker followed by GitLab Auto DevOps',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928300000,
            location: 'Visualization Room',
            name: 'American Express Workshop - Interactive choose-your-own-adventure game',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547929200000,
            location: 'Marston 2nd Floor',
            name: 'SNACK RELEASE!!! by InfoTech',
            startTime: 1547928000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'CSE E121',
            name: 'Data Science with Pokemon',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928900000,
            location: 'CSE E222',
            name: 'Google Lightning Talk - using Google Cloud Platform solutions for apps and prototypes',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'Marston Breezeway',
            name: 'Spicy Ramen Challenge by Facebook',
            startTime: 1547928000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'CSE E221',
            name: 'Lock Picking',
            startTime: 1547929800000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547933400000,
            location: 'Marston Breezeway',
            name: 'Dodgeball',
            startTime: 1547931600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547935200000,
            location: 'Marston Breezeway',
            name: 'RealTruck Workshop - Progressive JavaScript Framework',
            startTime: 1547931600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: 'Marston 2nd Floor',
            name: 'Cup Stacking MLH',
            startTime: 1547933400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547938800000,
            location: 'Marston 2nd Floor',
            name: 'POWER HOUR - RealTruck',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547936100000,
            location: 'CSE E222',
            name: 'Infinite Energy Lightning Talk 2 - Functional Programming',
            startTime: 1547935200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: 'CSE E220',
            name: 'Rubik\'s Competition by Infinite Energy',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937900000,
            location: 'CSE E221',
            name: 'Ultimate Software Lightning Talk',
            startTime: 1547937000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: 'CSE E121',
            name: 'Trivia by JP Morgan',
            startTime: 1547946000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547953200000,
            location: 'Marston Breezeway',
            name: 'NERF War by ExxonMobil',
            startTime: 1547949600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547944200000,
            location: 'Marston Breezeway',
            name: 'Piesanos Dinner by RealTruck',
            startTime: 1547938800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'From Dominoes',
            endTime: 1547964000000,
            location: 'Marston 2nd Floor',
            name: 'Dominoes Midnight Snack',
            startTime: 1547960400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547955000000,
            location: 'Visualization Room',
            name: 'Smash Bros Tournament by Google',
            startTime: 1547951400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: 'Marston Breezeway',
            name: 'Publix Breakfast',
            startTime: 1547989200000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547989200000,
            location: '',
            name: 'DevPost Submissions Close',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: 'MADE @ UF',
            name: 'Demo Practice Activity',
            startTime: 1547989200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'Prizes given to Winner',
            endTime: 1547994600000,
            location: '',
            name: 'SwampCup Winner Announced',
            startTime: 1547992800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548000000000,
            location: 'Marston Breezeway',
            name: 'Publix Lunch',
            startTime: 1547996400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: null,
            location: '',
            name: 'HACKING ENDS',
            startTime: 1547996400000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548003600000,
            location: 'Marston 3rd Floor',
            name: 'Demo Fair Round 1',
            startTime: 1547999100000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548009000000,
            location: 'Marston 3rd Floor',
            name: 'Demo Fair Round 2',
            startTime: 1548004500000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548012300000,
            location: 'Visualization Room',
            name: 'VIP Top 3 Deliberations',
            startTime: 1548011700000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548018000000,
            location: 'Carleton',
            name: 'Closing Ceremonies',
            startTime: 1548012600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548019800000,
            location: 'HUB Bus Stop',
            name: 'Buses Depart',
            startTime: 1548019800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
    ];
    
    static fridayEvents = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: 'Marston Breezeway',
            name: 'Sponsors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: 'Marston Breezeway',
            name: 'Mentors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547857800000,
            location: 'Marston Breezeway',
            name: 'Hacker Check-In',
            startTime: 1547850600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: 'Marston Breezeway',
            name: 'Bolay Dinner',
            startTime: 1547852400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: 'CSE E222',
            name: 'Team Building Activity',
            startTime: 1547854200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547863200000,
            location: 'Carleton',
            name: 'Opening Ceremony',
            startTime: 1547859600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547866800000,
            location: 'Marston Basement',
            name: 'Sponsor Fair',
            startTime: 1547863200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: null,
            location: '',
            name: 'Hacking Begins!!',
            startTime: 1547866800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: 'Visualization Room',
            name: 'SwampTank Activity',
            startTime: 1547869500000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: 'CSE E222',
            name: 'Intro to Git and Github',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547872500000,
            location: 'CSE E119',
            name: 'Survival Guide w/ JP Morgan',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
    ];

    static saturdayEvents = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: 'Marston 2nd Floor',
            name: 'Midnight Snack from KIND',
            startTime: 1547874000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'quarterHalf',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547876700000,
            location: 'CSE E119',
            name: 'Intro to Frontend (HTML/CSS)',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: 'CSE E221',
            name: 'iOS Development in Swift',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547881200000,
            location: 'CSE E119',
            name: 'VR on the Web',
            startTime: 1547877600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547878800000,
            location: 'CSE E220',
            name: 'Extreme Rock Paper Scissors',
            startTime: 1547877600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547911800000,
            location: 'Marston 2nd Floor',
            name: 'Ping Pong Tournament by InfoTech',
            startTime: 1547908200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547884800000,
            location: 'CSE E220',
            name: 'Intro to Reverse Engineering',
            startTime: 1547881200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547902800000,
            location: 'Marston Breezeway',
            name: 'Slime Station by Microsoft',
            startTime: 1547899200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547906400000,
            location: 'Marston Breezeway',
            name: 'Flying Biscuit Breakfast',
            startTime: 1547902800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: 'quarterHalf',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: 'Visualization Room',
            name: 'Citi Workshop - Nontechnical skills that set you apart for internships',
            startTime: 1547946000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: 'CSE E222',
            name: 'Building a Backend with Python and Flask',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547912700000,
            location: 'CSE E220',
            name: 'Microsoft Lightning talk - Getting Started with Artificial Intelligence and Machine Learning',
            startTime: 1547911800000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: 'Marston 2nd Floor',
            name: 'Snack Release by Amex',
            startTime: 1547913000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917200000,
            location: 'Marston Breezeway',
            name: 'Pancake Art',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: 'Marston Breezeway',
            name: 'Musical Chairs by Ultimate Software',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: 'CSE E221',
            name: 'Pitching Your New Business Venture',
            startTime: 1547913600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919000000,
            location: 'CSE E220',
            name: 'Advanced Frontend (Angular/React)',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917500000,
            location: 'CSE E121',
            name: 'InfoTech Workshop',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547920800000,
            location: 'Marston 2nd Floor',
            name: 'POWER HOUR - Citi',
            startTime: 1547917200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919300000,
            location: 'CSE E221',
            name: 'Home Depot Workshop - Intro to Docker',
            startTime: 1547917200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547922600000,
            location: 'Marston Breezeway',
            name: 'Therapy Dogs by Realtruck',
            startTime: 1547919000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: 'Marston Breezeway',
            name: 'Mi Apa Lunch by Citi',
            startTime: 1547920800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: 'Marston Breezeway',
            name: 'Chubby Bunny Game by Amex',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: 'Visualization Room',
            name: 'Jackbox Games by Home Depot',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547927100000,
            location: 'CSE E220',
            name: 'ExxonMobil Lightning Talk - Live demo on full stack web application using React, Express (Node.js) and Mongo',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: 'Marston 2nd Floor',
            name: 'Paper Airplane Comp',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547927100000,
            location: 'CSE E221',
            name: 'Infinite Energy Lightning talk 1 - Intro to Docker followed by GitLab Auto DevOps',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928300000,
            location: 'Visualization Room',
            name: 'American Express Workshop - Interactive choose-your-own-adventure game',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547929200000,
            location: 'Marston 2nd Floor',
            name: 'SNACK RELEASE!!! by InfoTech',
            startTime: 1547928000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'CSE E121',
            name: 'Data Science with Pokemon',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928900000,
            location: 'CSE E222',
            name: 'Google Lightning Talk - using Google Cloud Platform solutions for apps and prototypes',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'Marston Breezeway',
            name: 'Spicy Ramen Challenge by Facebook',
            startTime: 1547928000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'half',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: 'CSE E221',
            name: 'Lock Picking',
            startTime: 1547929800000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547933400000,
            location: 'Marston Breezeway',
            name: 'Dodgeball',
            startTime: 1547931600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'full',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547935200000,
            location: 'Marston Breezeway',
            name: 'RealTruck Workshop - Progressive JavaScript Framework',
            startTime: 1547931600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: 'Marston 2nd Floor',
            name: 'Cup Stacking MLH',
            startTime: 1547933400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547938800000,
            location: 'Marston 2nd Floor',
            name: 'POWER HOUR - RealTruck',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547936100000,
            location: 'CSE E222',
            name: 'Infinite Energy Lightning Talk 2 - Functional Programming',
            startTime: 1547935200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: 'CSE E220',
            name: 'Rubik\'s Competition by Infinite Energy',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'lightning',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937900000,
            location: 'CSE E221',
            name: 'Ultimate Software Lightning Talk',
            startTime: 1547937000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: 'CSE E121',
            name: 'Trivia by JP Morgan',
            startTime: 1547946000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'main',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547953200000,
            location: 'Marston Breezeway',
            name: 'NERF War by ExxonMobil',
            startTime: 1547949600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547944200000,
            location: 'Marston Breezeway',
            name: 'Piesanos Dinner by RealTruck',
            startTime: 1547938800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547955000000,
            location: 'Visualization Room',
            name: 'Smash Bros Tournament by Google',
            startTime: 1547951400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547956800000,
            location: 'Marston Basement, in front of elevators',
            name: 'SwampHacks Airpods Meet Up',
            startTime: 1547955900000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        }
    ];

    static sundayEvents = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'From Dominoes',
            endTime: 1547964000000,
            location: 'Marston 2nd Floor',
            name: 'Dominoes Midnight Snack',
            startTime: 1547960400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: 'Marston Breezeway',
            name: 'Publix Breakfast',
            startTime: 1547989200000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547989200000,
            location: '',
            name: 'DevPost Submissions Close',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: 'mini',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: 'MADE @ UF',
            name: 'Demo Practice Activity',
            startTime: 1547989200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'Prizes given to Winner',
            endTime: 1547994600000,
            location: '',
            name: 'SwampCup Winner Announced',
            startTime: 1547992800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548000000000,
            location: 'Marston Breezeway',
            name: 'Publix Lunch',
            startTime: 1547996400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: null,
            location: '',
            name: 'HACKING ENDS',
            startTime: 1547996400000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548003600000,
            location: 'Marston 3rd Floor',
            name: 'Demo Fair Round 1',
            startTime: 1547999100000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548009000000,
            location: 'Marston 3rd Floor',
            name: 'Demo Fair Round 2',
            startTime: 1548004500000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548012300000,
            location: 'Visualization Room',
            name: 'VIP Top 3 Deliberations',
            startTime: 1548011700000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548018000000,
            location: 'Carleton',
            name: 'Closing Ceremonies',
            startTime: 1548012600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548019800000,
            location: 'HUB Bus Stop',
            name: 'Buses Depart',
            startTime: 1548019800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
    ];

}